
name: CD

on:
  push:
    branches: [ production ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set up Node and NPM
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '16'
      - run: npm install
      - run: npx mix --production
      - name: Commit built assets
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -B deploy
          git add -f public/
          git commit -m "Build front-end assets"
          git push -f origin deploy
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ec2-3-133-119-84.us-east-2.compute.amazonaws.com
          password: ${{ secrets.SSH_KEY }}
          script: 'cd /var/www/efiehub && ./server_deploy.sh'
